CREATE TABLE IF NOT EXISTS sources (
  code VARCHAR(10) PRIMARY KEY NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS satellites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  catalog_id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  launch_date DATE NOT NULL,
  orbit_type VARCHAR(50),
  source_code VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS satellite_tle (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  catalog_id VARCHAR(100),
  tle_line1 TEXT NOT NULL,
  tle_line2 TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sources (code, description) VALUES
  ('AB', 	'Arab Satellite Communications Organization'),
  ('ABS', 	'Asia Broadcast Satellite'),
  ('AC', 	'Asia Satellite Telecommunications Company (ASIASAT)'),
  ('ALG', 	'Algeria'),
  ('ANG', 	'Angola'),
  ('ARGN',	'Argentina'),
  ('ASRA',	'Austria'),
  ('AUS', 	'Australia'),
  ('AZER',	'Azerbaijan'),
  ('BEL', 	'Belgium'),
  ('BELA',	'Belarus'),
  ('BERM',	'Bermuda'),
  ('BGD', 	'Peoples Republic of Bangladesh'),
  ('BHUT',	'Kingdom of Bhutan'),
  ('BOL', 	'Bolivia'),
  ('BRAZ',	'Brazil'),
  ('BUL',	'Bulgaria'),
  ('CA', 	'Canada'),
  ('CHBZ',	'China/Brazil'),
  ('CHLE',	'Chile'),
  ('CIS', 	'Commonwealth of Independent States (former USSR)'),
  ('COL', 	'Colombia'),
  ('CRI', 	'Republic of Costa Rica'),
  ('CZCH',	'Czech Republic (former Czechoslovakia)'),
  ('DEN', 	'Denmark'),
  ('ECU', 	'Ecuador'),
  ('EGYP',	'Egypt'),
  ('ESA', 	'European Space Agency'),
  ('ESRO',	'European Space Research Organization'),
  ('EST',	'Estonia'),
  ('EUME',	'European Organization for the'),
  ('Exploitation', 'of Meteorological Satellites (EUMETSAT)'),
  ('EUTE',	'European Telecommunications Satellite Organization (EUTELSAT)'),
  ('FGER',	'France/Germany'),
  ('FIN', 	'Finland'),
  ('FR', 	'France'),
  ('FRIT',	'France/Italy'),
  ('GER', 	'Germany'),
  ('GHA', 	'Republic of Ghana'),
  ('GLOB',	'Globalstar'),
  ('GREC',	'Greece'),
  ('GRSA',	'Greece/Saudi Arabia'),
  ('GUAT',	'Guatemala'),
  ('HUN', 	'Hungary'),
  ('IM', 	'International Mobile Satellite Organization (INMARSAT)'),
  ('IND', 	'India'),
  ('INDO',	'Indonesia'),
  ('IRAN',	'Iran'),
  ('IRAQ',	'Iraq'),
  ('IRID',	'Iridium'),
  ('ISRA',	'Israel'),
  ('ISRO',	'Indian Space Research Organisation'),
  ('ISS', 	'International Space Station'),
  ('IT', 	'Italy'),
  ('ITSO',	'International Telecommunications Satellite Organization (INTELSAT)'),
  ('JPN', 	'Japan'),
  ('KAZ', 	'Kazakhstan'),
  ('KEN', 	'Republic of Kenya'),
  ('LAOS',	'Laos'),
  ('LKA',	'Democratic Socialist Republic of Sri Lanka'),
  ('LTU', 	'Lithuania'),
  ('LUXE',	'Luxembourg'),
  ('MA', 	'Morroco'),
  ('MALA',	'Malaysia'),
  ('MDA', 	'Republic of Moldova'),
  ('MEX', 	'Mexico'),
  ('MMR', 	'Republic of the Union of Myanmar'),
  ('MNG', 	'Mongolia'),
  ('MUS', 	'Mauritius'),
  ('NATO',	'North Atlantic Treaty Organization'),
  ('NETH',	'Netherlands'),
  ('NICO',	'New ICO'),
  ('NIG', 	'Nigeria'),
  ('NKOR',	'Democratic People''s Republic of Korea'),
  ('NOR', 	'Norway'),
  ('NPL', 	'Federal Democratic Republic of Nepal'),
  ('NZ', 	'New Zealand'),
  ('O3B', 	'O3b Networks'),
  ('ORB', 	'ORBCOMM'),
  ('PAKI',	'Pakistan'),
  ('PERU',	'Peru'),
  ('POL', 	'Poland'),
  ('POR', 	'Portugal'),
  ('PRC', 	'People''s Republic of China'),
  ('PRY', 	'Republic of Paraguay'),
  ('PRES',	'People''s Republic of China/European Space Agency'),
  ('QAT', 	'State of Qatar'),
  ('RASC',	'RascomStar-QAF'),
  ('ROC', 	'Taiwan (Republic of China)'),
  ('ROM', 	'Romania'),
  ('RP', 	'Philippines (Republic of the Philippines)'),
  ('RWA', 	'Republic of Rwanda'),
  ('SAFR',	'South Africa'),
  ('SAUD',	'Saudi Arabia'),
  ('SDN', 	'Republic of Sudan'),
  ('SEAL',	'Sea Launch'),
  ('SES',	'SES'),
  ('SGJP',	'Singapore/Japan'),
  ('SING',	'Singapore'),
  ('SKOR',	'Republic of Korea'),
  ('SPN', 	'Spain'),
  ('STCT',	'Singapore/Taiwan'),
  ('SVN',	'Slovenia'),
  ('SWED',	'Sweden'),
  ('SWTZ',	'Switzerland'),
  ('TBD', 	'To Be Determined'),
  ('THAI',	'Thailand'),
  ('TMMC',	'Turkmenistan/Monaco'),
  ('TUN', 	'Republic of Tunisia'),
  ('TURK',	'Turkey'),
  ('UAE', 	'United Arab Emirates'),
  ('UK', 	'United Kingdom'),
  ('UKR', 	'Ukraine'),
  ('UNK', 	'Unknown'),
  ('URY', 	'Uruguay'),
  ('US', 	'United States'),
  ('USBZ',	'United States/Brazil'),
  ('VENZ',	'Venezuela'),
  ('VTNM',	'Vietnam');

INSERT INTO satellites (catalog_id, name, launch_date, orbit_type, source_code) VALUES
  ('25544', 'ISS (ZARYA)', '1998-11-20', 'ORB', 'ISS'),
  ('36086', 'POISK', '2009-11-10', 'DOC', 'ISS'),
  ('43556', 'AEROCUBE 12A', '2018-05-21', 'ORB', 'US'),
  ('43557', 'AEROCUBE 12B', '2018-05-21', 'ORB', 'US'),
  ('45265', 'ICS-EF (ISS DEB)', '1998-11-20', 'ORB', 'JPN'),
  ('47853', 'ISS DEB', '1998-11-20', 'ORB', 'JPN'),
  ('47976', 'MMSATS-1', '1998-11-20', 'ORB', 'MMR'),
  ('48274', 'CSS (TIANHE)', '2021-04-29', 'ORB', 'PRC'),
  ('49044', 'ISS (NAUKA)', '2021-07-21', 'DOC', 'CIS'),
  ('49271', 'FREGAT DEB', '2011-07-18', 'ORB', 'CIS'),
  ('52148', 'KITSUNE', '1998-11-20', 'ORB', 'JPN'),
  ('53239', 'CSS (WENTIAN)', '2022-07-24', 'DOC', 'PRC'),
  ('53462', 'HSU-SAT1', '1998-11-20', 'ORB', 'JPN'),
  ('53767', 'D3', '1998-11-20', 'ORB', 'US'),
  ('53768', 'BEAVERCUBE', '1998-11-20', 'ORB', 'US'),
  ('53769', 'CLICK-A', '1998-11-20', 'ORB', 'US'),
  ('53772', 'ISS DEB', '1998-11-20', 'ORB', 'CIS'),
  ('53879', 'SOYUZ-MS 22', '2022-09-21', 'DOC', 'CIS'),
  ('53963', 'CREW DRAGON 5', '2022-10-05', 'DOC', 'US'),
  ('54216', 'CSS (MENGTIAN)', '2022-10-31', 'DOC', 'PRC'),
  ('54232', 'CYGNUS NG-18', '2022-11-07', 'DOC', 'US'),
  ('54237', 'TIANZHOU-5', '2022-11-12', 'DOC', 'PRC'),
  ('54379', 'SHENZHOU-15', '2022-11-29', 'DOC', 'PRC'),
  ('54534', '1998-067UL', '1998-11-20', 'ORB', 'JPN'),
  ('54535', '1998-067UM', '1998-11-20', 'ORB', 'JPN'),
  ('54536', '1998-067UN', '1998-11-20', 'ORB', 'JPN'),
  ('54537', '1998-067UP', '1998-11-20', 'ORB', 'JPN'),
  ('54816', 'XW-4 (CAS-10)', '2021-04-29', 'ORB', 'PRC'),
  ('55123', 'MARIO', '1998-11-20', 'ORB', 'US'),
  ('55124', 'NUTSAT', '1998-11-20', 'ORB', 'ROC'),
  ('55125', 'LORIS', '1998-11-20', 'ORB', 'CA'),
  ('55126', 'ORCASAT', '1998-11-20', 'ORB', 'CA'),
  ('55128', 'TJREVERB', '1998-11-20', 'ORB', 'US'),
  ('55129', 'SPORT', '1998-11-20', 'ORB', 'BRAZ'),
  ('55130', 'PETITSAT', '1998-11-20', 'ORB', 'US'),
  ('55181', 'SS-1', '1998-11-20', 'ORB', 'INDO'),
  ('55182', 'HSKSAT', '1998-11-20', 'ORB', 'JPN'),
  ('55183', 'OPTIMAL-1', '1998-11-20', 'ORB', 'JPN'),
  ('55448', 'ISS DEB (SPX-26 IPA FSE)', '1998-11-20', 'ORB', 'US'),
  ('55560', 'PROGRESS-MS 22', '2023-02-09', 'DOC', 'CIS'),
  ('55688', 'SOYUZ-MS 23', '2023-02-24', 'ORB', 'CIS'),
  ('55689', 'SL-4 R/B', '2023-02-24', 'ORB', 'CIS');
